name: lutris
version: '0.5.1.2'
summary: Lutris client - Open Source gaming platform for GNU/Linux.
description: Lutris is an open source gaming platform that makes gaming on 
Linux easier by managing, installing and providing optimal settings for games.
  
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: i386
  - build-on: amd64
  

apps:
  lutris:
    command: bin/lutris
    plugs:
      - home
      - network
      - removable-media

parts:
lutris:
    plugin: python
    python-version: python3
    source: https://github.com/lutris/lutris.git
    stage-packages:
      - python-six
      
    source-type: git
    override-pull: |
     git clone https://github.com/lutris/lutris.git src/github.com/lutris/lutris
       cd src/github.com/lutris/lutris
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/lutris/lutris
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/lutris/lutris/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/lutris/lutris/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/lutris
    build-snaps:
      - 
   build-packages:
      - git
      - sed
     
